### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shannonharrison118**
updated readme file:
- fix broken link in beginning to timer itself and added description
- expanded installation instructions for requirements and source files themselves
- added a section of explanation of where to find important features of code
- added link to redux support and included test suite name

### CODE REVIEW

**Review by iagodahlem — CHANGES_REQUESTED** [review]
Hey @shannonharrison118! Thanks for your contribution. I liked the improvements in the documentation and thanks for fixing the main website link, didn't notice it was linking to the wrong one. Left some feedback before we can merge it.

**Comment by iagodahlem** [comment]
I also just fixed the deploys previews from Netlify, when you push a new commit it should pass if nothing is breaking.

**Comment by shannonharrison118** [comment]
all these changes sound good! i can update these changes.

**Review by iagodahlem — APPROVED** [review]

**Comment by iagodahlem** [comment]
Looks good! 🚀

**Pull request merged**
